/**
 * @description       :
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             :
 * @last modified on  : 02-21-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 **/
public class AllRecipeServiceImpl implements IAllRecipeService {
  public AllRecipeServiceImpl() {
  }

  public List<RecipeIngredient__c> getAllRecipes() {
    return new List<RecipeIngredient__c>();
  }

  public List<RecipeIngredient__c> serachRecipes(String serachByText) {
    return new List<RecipeIngredient__c>();
  }
}
